### PR TITLE
Updated for laravel 6.0

### PR DESCRIPTION
**Pull request by jdanino**
Updated composer.json and changed array helper method call to comply with 6.0

### CODE REVIEW

**Review by MartinDinkov — APPROVED** [review]
Still waiting for Laravel 6.0 compatibility of your package. This pull request seems legit.

**Comment by vicgonvt** [comment]
Any chance we can get this merged?

Thanks!

**Comment by hashemabucu** [comment]
laravel gmail configuration not work............. please give me solution

**Comment by SuperStar518** [comment]
Laravel support is impossible?

**Comment by gcphost** [comment]
bump

**Comment by themrflibble** [comment]
Are there any plans to make this support Laravel 7/8 ?

**Comment by howdu** [comment]
This project looks to be abandoned but there's this one instead that works with Larvavel 8/9 https://github.com/joelbutcher/laravel-facebook-graph

**Pull request closed without merging**
